### ISSUE TITLE
Navigation style

### ISSUE THREAD

**Issue by eko24ive** [VitaZubkova/home-work_4#1]
Your navigation is differs from desing:
![image](https://cloud.githubusercontent.com/assets/25591824/23180385/ea27ddce-f879-11e6-9965-1285e627836b.png)

Change it to:
![image](https://cloud.githubusercontent.com/assets/25591824/23180367/e07b8c08-f879-11e6-82f1-87fa08131e2c.png)

For hover link use this design:
![image](https://cloud.githubusercontent.com/assets/25591824/23180388/effdf2ba-f879-11e6-9619-268f59953a4d.png)

**Comment by VitaZubkova** [comment]
If I understand correctly mistake.
I corrected

**Comment by eko24ive** [comment]
Awesome !
You did really well !
